

services:
  # 1. Dịch vụ Database (MySQL)
  mysql_db:
    image: mysql:8.0
    container_name: hai_san_db
    restart: always
    environment:
      MYSQL_DATABASE: thuy_hai_san
      # Root vẫn cần có pass (quyền tối cao)
      MYSQL_ROOT_PASSWORD: 'm5!xNd21x2)rc(l*' 
      # Tạo account admin riêng theo ý Phú
      MYSQL_USER: admin
      MYSQL_PASSWORD: 'm5!xNd21x2)rc(l*'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # 2. Dịch vụ Backend (Laravel)
  backend:
      build:
        context: ./thuy_hai_san_backend
      container_name: thuy_hai_san_backend
      volumes:
        - ./thuy_hai_san_backend:/var/www
      ports:
        - "8000:8000"
      environment:
        - DB_CONNECTION=mysql
        - DB_HOST=mysql_db
        - DB_PORT=3306
        - DB_DATABASE=thuy_hai_san
        - DB_USERNAME=admin                # QUAN TRỌNG: Khai báo user admin ở đây
        - DB_PASSWORD='m5!xNd21x2)rc(l*'
      depends_on:
        - mysql_db

  # 3. Dịch vụ Frontend (ReactJS)
  frontend:
    build:
      context: ./thuy_hai_san_frontend
    container_name: thuy_hai_san_frontend
    volumes:
      - ./thuy_hai_san_frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data: # Lưu trữ dữ liệu DB bền vững, không bị mất khi tắt container