<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 4,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '670000.00',
                'status' => 'processing',
                'shipping_adr' => '94B2 Trần Khắc Chân P. Đức Nhuận Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-27 16:11:51',
                'updated_at' => '2026-05-05 14:52:27',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 4,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '1120000.00',
                'status' => 'completed',
                'shipping_adr' => '94B2 Trần Khắc Chân P. Đức Nhuận Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-27 16:23:47',
                'updated_at' => '2026-05-05 14:56:11',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 4,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '1100000.00',
                'status' => 'processing',
                'shipping_adr' => '94B2 Trần Khắc Chân P. Đức Nhuận Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-27 16:49:34',
                'updated_at' => '2026-05-05 14:52:16',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 2,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '1650000.00',
                'status' => 'processing',
                'shipping_adr' => 'Đại học Trà Vinh, số 126 Nguyễn Thiện Thành',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-27 16:57:02',
                'updated_at' => '2026-05-05 14:52:07',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 4,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '1950000.00',
                'status' => 'processing',
                'shipping_adr' => 'dvdsv dfs df',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-27 17:54:30',
                'updated_at' => '2026-05-05 14:51:58',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 4,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '670000.00',
                'status' => 'processing',
                'shipping_adr' => 'dsfdf',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-28 20:03:34',
                'updated_at' => '2026-05-05 14:52:36',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 4,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '930000.00',
                'status' => 'processing',
                'shipping_adr' => 'sfd fs fd',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-28 20:06:16',
                'updated_at' => '2026-05-05 14:52:46',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 4,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '1920000.00',
                'status' => 'processing',
                'shipping_adr' => '94B2 Trần Khắc Chân P. Đức Nhuận Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-28 20:56:57',
                'updated_at' => '2026-05-05 14:52:56',
            ),
            8 => 
            array (
                'id' => 10,
                'user_id' => 4,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '2030000.00',
                'status' => 'completed',
                'shipping_adr' => '94B2 Trần Khắc Chân P. Đức Nhuận Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-28 21:27:09',
                'updated_at' => '2026-05-15 08:34:27',
            ),
            9 => 
            array (
                'id' => 11,
                'user_id' => 4,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '660000.00',
                'status' => 'pending',
                'shipping_adr' => 'sdf fsdf dfdsf',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-28 21:29:21',
                'updated_at' => '2026-04-28 21:29:21',
            ),
            10 => 
            array (
                'id' => 12,
                'user_id' => 4,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '3010000.00',
                'status' => 'completed',
                'shipping_adr' => 'ể 45435 43543 5',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-28 21:32:47',
                'updated_at' => '2026-05-15 08:34:03',
            ),
            11 => 
            array (
                'id' => 13,
                'user_id' => 4,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '760000.00',
                'status' => 'processing',
                'shipping_adr' => '94B2 Trần Khắc Chân P. Đức Nhuận Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-28 21:43:25',
                'updated_at' => '2026-05-12 15:09:07',
            ),
            12 => 
            array (
                'id' => 20,
                'user_id' => 2,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '8740000.00',
                'status' => 'processing',
                'shipping_adr' => 'Đại học Trà Vinh, số 126 Nguyễn Thiện Thành',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-28 22:06:15',
                'updated_at' => '2026-05-04 21:32:37',
            ),
            13 => 
            array (
                'id' => 21,
                'user_id' => 2,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '830000.00',
                'status' => 'completed',
                'shipping_adr' => 'sfds fdsf dsf',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-28 23:04:10',
                'updated_at' => '2026-05-15 08:33:37',
            ),
            14 => 
            array (
                'id' => 22,
                'user_id' => 2,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '1230000.00',
                'status' => 'completed',
                'shipping_adr' => 'sdfadsfds',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-29 12:43:31',
                'updated_at' => '2026-05-15 08:33:25',
            ),
            15 => 
            array (
                'id' => 23,
                'user_id' => 2,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '950000.00',
                'status' => 'completed',
                'shipping_adr' => 'ear a êr ẻ',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-29 12:49:02',
                'updated_at' => '2026-05-05 14:56:05',
            ),
            16 => 
            array (
                'id' => 24,
                'user_id' => 4,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '950000.00',
                'status' => 'completed',
                'shipping_adr' => '94B2 Trần Khắc Chân P. Đức Nhuận Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-29 13:06:28',
                'updated_at' => '2026-05-15 08:33:10',
            ),
            17 => 
            array (
                'id' => 25,
                'user_id' => 5,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '1150000.00',
                'status' => 'processing',
                'shipping_adr' => '418 Trần Phú P. An Đông Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-29 13:08:47',
                'updated_at' => '2026-05-04 21:32:16',
            ),
            18 => 
            array (
                'id' => 26,
                'user_id' => 5,
                'customer_name' => NULL,
                'customer_phone' => NULL,
                'total_price' => '500000.00',
                'status' => 'completed',
                'shipping_adr' => '418 Trần Phú P. An Đông Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => '',
                'created_at' => '2026-04-29 13:34:03',
                'updated_at' => '2026-05-05 13:31:44',
            ),
            19 => 
            array (
                'id' => 27,
                'user_id' => 999999999,
                'customer_name' => 'toi',
                'customer_phone' => '0888128277',
                'total_price' => '530000.00',
                'status' => 'completed',
                'shipping_adr' => '418 Trần Phú P. An Đông Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-03 22:38:51',
                'updated_at' => '2026-05-05 13:31:34',
            ),
            20 => 
            array (
                'id' => 28,
                'user_id' => 5,
                'customer_name' => 'Gia Nghi',
                'customer_phone' => '0888888888',
                'total_price' => '1050000.00',
                'status' => 'cancelled',
                'shipping_adr' => '43 fa f sdf',
                'Delivery_hours' => '11',
                'note' => 'ádfasf',
                'created_at' => '2026-05-03 22:47:31',
                'updated_at' => '2026-05-04 13:08:21',
            ),
            21 => 
            array (
                'id' => 29,
                'user_id' => 999999999,
                'customer_name' => 'Gia Nghi',
                'customer_phone' => '088888888',
                'total_price' => '780000.00',
                'status' => 'processing',
                'shipping_adr' => 'Xa Lam TUyen asdf',
                'Delivery_hours' => 'f',
                'note' => NULL,
                'created_at' => '2026-05-04 12:21:39',
                'updated_at' => '2026-05-04 12:35:03',
            ),
            22 => 
            array (
                'id' => 30,
                'user_id' => 999999999,
                'customer_name' => 'dfads',
                'customer_phone' => '35345435345',
                'total_price' => '1680000.00',
                'status' => 'processing',
                'shipping_adr' => 'dsf sdf sdaf',
                'Delivery_hours' => 'sdf',
                'note' => NULL,
                'created_at' => '2026-05-05 13:30:03',
                'updated_at' => '2026-05-05 13:31:24',
            ),
            23 => 
            array (
                'id' => 31,
                'user_id' => 4,
                'customer_name' => 'Kim Hằng',
                'customer_phone' => '0888517980',
                'total_price' => '930000.00',
                'status' => 'completed',
                'shipping_adr' => '94B2 Trần Khắc Chân P. Đức Nhuận Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-05 13:30:28',
                'updated_at' => '2026-05-05 14:50:45',
            ),
            24 => 
            array (
                'id' => 32,
                'user_id' => 4,
                'customer_name' => 'ewre',
                'customer_phone' => 'ưe3543534534',
                'total_price' => '1900000.00',
                'status' => 'completed',
                'shipping_adr' => 'sdfsdf',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-05 13:54:27',
                'updated_at' => '2026-05-05 13:55:50',
            ),
            25 => 
            array (
                'id' => 33,
                'user_id' => 4,
                'customer_name' => 'Kim Hằng',
                'customer_phone' => '0888517980',
                'total_price' => '250000.00',
                'status' => 'processing',
                'shipping_adr' => '94B2 Trần Khắc Chân P. Đức Nhuận Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-06 22:33:30',
                'updated_at' => '2026-05-12 15:08:52',
            ),
            26 => 
            array (
                'id' => 34,
                'user_id' => 4,
                'customer_name' => 'dsf',
                'customer_phone' => '5435435435',
                'total_price' => '1150000.00',
                'status' => 'processing',
                'shipping_adr' => 'fd sdf sdf',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-06 22:35:02',
                'updated_at' => '2026-05-12 15:08:45',
            ),
            27 => 
            array (
                'id' => 35,
                'user_id' => 999999999,
                'customer_name' => 'sdaf',
                'customer_phone' => '34534 345 43534',
                'total_price' => '1330000.00',
                'status' => 'processing',
                'shipping_adr' => 'sdf dsfsad f',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-07 20:13:40',
                'updated_at' => '2026-05-12 15:08:37',
            ),
            28 => 
            array (
                'id' => 36,
                'user_id' => 999999999,
                'customer_name' => 'dg',
                'customer_phone' => 'ggggg',
                'total_price' => '160000.00',
                'status' => 'shipping',
                'shipping_adr' => 'gggggggggggggg',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-07 20:15:12',
                'updated_at' => '2026-05-07 21:36:25',
            ),
            29 => 
            array (
                'id' => 37,
                'user_id' => 4,
                'customer_name' => 'Kim Hằng',
                'customer_phone' => '0888517980',
                'total_price' => '2480000.00',
                'status' => 'processing',
                'shipping_adr' => '94B2 Trần Khắc Chân P. Đức Nhuận Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-07 20:19:11',
                'updated_at' => '2026-05-07 20:38:18',
            ),
            30 => 
            array (
                'id' => 38,
                'user_id' => 4,
                'customer_name' => 'Kim Hằng',
                'customer_phone' => '0888517980',
                'total_price' => '1580000.00',
                'status' => 'processing',
                'shipping_adr' => '94B2 Trần Khắc Chân P. Đức Nhuận Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-07 20:27:54',
                'updated_at' => '2026-05-07 20:38:09',
            ),
            31 => 
            array (
                'id' => 39,
                'user_id' => 999999999,
                'customer_name' => 'd',
                'customer_phone' => 'dsfdfdsf',
                'total_price' => '180000.00',
                'status' => 'completed',
                'shipping_adr' => 'dsfdsf',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-07 20:29:43',
                'updated_at' => '2026-05-07 21:36:12',
            ),
            32 => 
            array (
                'id' => 40,
                'user_id' => 5,
                'customer_name' => 'toi',
                'customer_phone' => '0888128277',
                'total_price' => '240000.00',
                'status' => 'processing',
                'shipping_adr' => '418 Trần Phú P. An Đông Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-07 20:36:43',
                'updated_at' => '2026-05-07 20:37:52',
            ),
            33 => 
            array (
                'id' => 41,
                'user_id' => 999999999,
                'customer_name' => '4',
                'customer_phone' => '4444444444',
                'total_price' => '330000.00',
                'status' => 'processing',
                'shipping_adr' => '4444444444',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-07 20:41:37',
                'updated_at' => '2026-05-07 21:36:05',
            ),
            34 => 
            array (
                'id' => 42,
                'user_id' => 1,
                'customer_name' => 'Phú Trà Vinh',
                'customer_phone' => '0123456789',
                'total_price' => '1330000.00',
                'status' => 'completed',
                'shipping_adr' => 'Đại học Trà Vinh, số 126 Nguyễn Thiện Thành',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-08 14:53:54',
                'updated_at' => '2026-05-08 15:17:49',
            ),
            35 => 
            array (
                'id' => 43,
                'user_id' => 999999999,
                'customer_name' => '333',
                'customer_phone' => '333333333',
                'total_price' => '1660000.00',
                'status' => 'processing',
                'shipping_adr' => '3dsad 3 3 2 32',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-08 15:15:49',
                'updated_at' => '2026-05-08 15:17:37',
            ),
            36 => 
            array (
                'id' => 44,
                'user_id' => 4,
                'customer_name' => 'Kim Hằng',
                'customer_phone' => '0888517980',
                'total_price' => '1480000.00',
                'status' => 'shipping',
                'shipping_adr' => '94B2 Trần Khắc Chân P. Đức Nhuận Tp. Hồ Chí Minh',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-08 15:16:42',
                'updated_at' => '2026-05-12 15:08:12',
            ),
            37 => 
            array (
                'id' => 45,
                'user_id' => 999999999,
                'customer_name' => 'Toi',
                'customer_phone' => '000000000',
                'total_price' => '60000.00',
                'status' => 'pending',
                'shipping_adr' => '0 co dia chi',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-15 07:42:31',
                'updated_at' => '2026-05-15 07:42:31',
            ),
            38 => 
            array (
                'id' => 46,
                'user_id' => 999999999,
                'customer_name' => 'Toi',
                'customer_phone' => '000000000',
                'total_price' => '60000.00',
                'status' => 'completed',
                'shipping_adr' => '0 co dia chi',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-15 07:46:53',
                'updated_at' => '2026-05-15 08:28:33',
            ),
            39 => 
            array (
                'id' => 47,
                'user_id' => 999999999,
                'customer_name' => 'Thiện',
                'customer_phone' => '0888888888',
                'total_price' => '1580000.00',
                'status' => 'pending',
                'shipping_adr' => '000 Đường số mấy không biết',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-15 08:18:15',
                'updated_at' => '2026-05-15 08:18:15',
            ),
            40 => 
            array (
                'id' => 48,
                'user_id' => 1,
                'customer_name' => 'Phú Trà Vinh',
                'customer_phone' => '0123456789',
                'total_price' => '4730000.00',
                'status' => 'completed',
                'shipping_adr' => 'Đại học Trà Vinh, số 126 Nguyễn Thiện Thành',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-15 08:35:22',
                'updated_at' => '2026-05-15 08:36:26',
            ),
            41 => 
            array (
                'id' => 49,
                'user_id' => 1,
                'customer_name' => 'Phú Trà Vinh',
                'customer_phone' => '0123456789',
                'total_price' => '2250000.00',
                'status' => 'completed',
                'shipping_adr' => 'Đại học Trà Vinh, số 126 Nguyễn Thiện Thành',
                'Delivery_hours' => NULL,
                'note' => NULL,
                'created_at' => '2026-05-15 08:35:58',
                'updated_at' => '2026-05-15 08:36:19',
            ),
        ));
        
        
    }
}